#!/bin/bash

#Assignment 1: System Report
#Name:  Nicolas Blouin
#Student Number: 200410446

#Script Description



source /etc/os-release
my_username=$USER
my_date=$(date)
my_hostname=$(hostname)

cat << EOF
$PRETTY_NAME
====================================================

Script Description:

This script will create a system information report
including system hardware, network, and system status
of the current machine.

====================================================

System Report Generated by: $my_username

Date & time of Report: $my_date

====================================================

System Information:
-------------------

The Current Hostname: $my_hostname


cpuModel=$(lscpu | grep 'Model name:')

$cpuModel


EOF
